python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=0 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.001 group=replica_cmlp_lightning_1_0_96 comments=lr_001
python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=0 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.0001 group=replica_cmlp_lightning_1_0_96 comments=lr_0001
python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=10 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.0001 group=replica_cmlp_lightning_1_10_96 comments=lr_0001
python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=1 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.0001 group=replica_cmlp_lightning_1_1_96 comments=lr_0001
python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=0.1 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.0001 group=replica_cmlp_lightning_1_'0.1'_96 comments=lr_0001
python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=0.01 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.0001 group=replica_cmlp_lightning_1_'0.01'_96 comments=lr_0001
python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=0.001 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.0001 group=replica_cmlp_lightning_1_'0.001'_96 comments=lr_0001
python main.py project=cmlp datamodule=replica modelmodule=cmlp modelmodule.weights.sdf_weight=1 modelmodule.weights.eik_weight=0.0001 modelmodule.net.decoder.out_dim=96 modelmodule.optimizer.lr=0.0001 group=replica_cmlp_lightning_1_'0.0001'_96 comments=lr_0001

