defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - _self_

model_checkpoint:
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val_error_avg"
  mode: "min"
  save_top_k: 5
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1

early_stopping:
  monitor: "val_error_avg"
  patience: 100
  mode: "min"