_target_: modelmodule.base.Module

net:
  _target_: model.tensorf.TensoRF
  xyz_min: [-2.67659784, -0.08062697, -4.83431278]
  xyz_max: [ 4.58195351,  3.04455779,  8.16458168]
  
  positional_encoder:
    _target_: model.encoder.positional_encoder.identity.PositionalEncoding
    in_dim: 3

  decoder: 
    _target_: model.decoder.kplane.KPlane
    resolution: [727, 314, 1300]
    num_components: 8
    init_weight: 
      _target_: torch.nn.init.uniform_
      _partial_: true
      a: 0.1
      b: 0.5
    decoder: 
      _target_: model.decoder.mlp.MLP
      _partial_: True
      num_layers: 2
      layer_width: 64
      out_dim: 1
      skip_connections: null
      activation: null


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0013
  weight_decay: 0.012


weights:
  sdf_weight: 1
  eik_weight: 0


